[versions]
assertk = "0.28.1"
kotlin = "2.2.0"
kotlinCoroutines = "1.10.2"
junitJupiter = "5.13.3"
turbine = "1.2.1"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }

# Test
test-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
test-junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
test-junitJupiter-launcher = { module = "org.junit.platform:junit-platform-launcher" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }